name: CI

# Run on every push or PR to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # 1. Grab your code
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Install deps & build
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      # 4. (Optional) Run tests
      - name: Run tests
        run: npm test -- --watchAll=false
